### ISSUE TITLE
getshopped site bug

### ISSUE THREAD

**Issue by szepeviktor** [wp-e-commerce/WP-e-Commerce#589]
``` css
.anythingFader div {
    width: 980px;
}
```

stretches `<div id="thumbNav">` above `<a class="arrow forward">></a>`
that is why the forward arrow cannot be clicked
